name: Test Sling Action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  actions-test:
    runs-on: ubuntu-latest
    env:
      TEST_PG_SLING_MASTER: ${{ secrets.TEST_PG_SLING_MASTER }}
      DEMO_POSTGRES: ${{ secrets.DEMO_POSTGRES }}
      SQLITE: ${{ secrets.SQLITE }}

    steps:
      - uses: actions/checkout@v2
      
      - name: List Connections
        uses: ./
        with:
          command: conns list

      - name: Test Old version
        uses: ./
        with:
          command: conns list
          version: 1.0.8
